#!/usr/bin/env python3
"""生成 gRPC Python 代码的脚本"""
import os
import subprocess
import sys
import re


def check_dependencies():
    """检查必要的依赖是否安装"""
    try:
        subprocess.check_call([sys.executable, "-c", "import grpc_tools"])
        print("✓ grpcio-tools 已安装")
        return True
    except (subprocess.CalledProcessError, ImportError):
        print("✗ 未安装 grpcio-tools，请先运行: pip install grpcio-tools")
        return False


def generate_proto():
    """生成 gRPC 代码"""
    proto_file = "chat.proto"

    # 确保存在 proto 文件
    if not os.path.exists(proto_file):
        print(f"错误: 找不到 {proto_file}")
        return False

    # 创建输出目录
    output_dir = "generated"
    os.makedirs(output_dir, exist_ok=True)

    print(f"生成 gRPC 代码...")
    print(f"Proto 文件: {proto_file}")
    print(f"输出目录: {output_dir}")

    # 生成 gRPC Python 代码
    cmd = [
        sys.executable, "-m", "grpc_tools.protoc",
        f"-I.",  # proto 文件搜索路径
        f"--python_out={output_dir}",
        f"--grpc_python_out={output_dir}",
        proto_file
    ]

    print(f"执行命令: {' '.join(cmd)}")

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        print("✓ 生成成功!")

        # 显示生成的文件
        generated_files = []
        for file in ["chat_pb2.py", "chat_pb2_grpc.py"]:
            file_path = os.path.join(output_dir, file)
            if os.path.exists(file_path):
                generated_files.append(file)
                print(f"  - {file}")

        if generated_files:
            # 修复导入路径
            fix_imports(output_dir)
            print("✓ 已修复导入语句")

        # 创建一个 __init__.py 文件
        init_file = os.path.join(output_dir, "__init__.py")
        with open(init_file, 'w') as f:
            f.write("# Generated gRPC code\n")
        print(f"✓ 创建 {init_file}")

        return True

    except subprocess.CalledProcessError as e:
        print(f"✗ 生成失败!")
        if e.stdout:
            print(f"标准输出: {e.stdout}")
        if e.stderr:
            print(f"错误输出: {e.stderr}")

        # 如果是因为 grpc_tools 未安装，给出安装建议
        if "No module named 'grpc_tools'" in e.stderr:
            print("\n请先安装依赖:")
            print("pip install grpcio grpcio-tools protobuf")

        return False


def fix_imports(output_dir):
    """修复 gRPC 生成的导入语句"""
    pb2_grpc_file = os.path.join(output_dir, "chat_pb2_grpc.py")

    if not os.path.exists(pb2_grpc_file):
        return

    with open(pb2_grpc_file, 'r', encoding='utf-8') as f:
        content = f.read()

    # 方法1：修复相对导入（如果 generated 目录在当前目录下）
    old_import = "import chat_pb2 as chat__pb2"
    new_import = "from . import chat_pb2 as chat__pb2"

    if old_import in content:
        content = content.replace(old_import, new_import)
        print(f"  修复了绝对导入 -> 相对导入")

    # 方法2：添加备用导入方式
    # 在文件开头添加注释和备用导入逻辑
    header_comment = """# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
# If you have import issues, try:
#   import sys
#   sys.path.append(os.path.dirname(__file__))
"""

    if not content.startswith(header_comment):
        content = header_comment + content

    with open(pb2_grpc_file, 'w', encoding='utf-8') as f:
        f.write(content)


def create_setup():
    """创建 setup.py 用于包安装"""
    setup_content = '''from setuptools import setup, find_packages

setup(
    name="grpc-chat-demo",
    version="1.0.0",
    packages=find_packages(),
    install_requires=[
        "grpcio>=1.60.0",
        "grpcio-tools>=1.60.0",
        "protobuf>=4.25.3",
    ],
    python_requires=">=3.7",
)
'''

    with open("setup.py", "w") as f:
        f.write(setup_content)
    print("✓ 创建 setup.py")


if __name__ == "__main__":
    print("=" * 50)
    print("gRPC 代码生成器")
    print("=" * 50)

    # 检查依赖
    if not check_dependencies():
        print("\n请先安装依赖:")
        print("  pip install grpcio grpcio-tools protobuf")
        print("或者运行: python install_deps.py")
        sys.exit(1)

    # 生成代码
    success = generate_proto()

    if success:
        print("\n" + "=" * 50)
        print("✓ 完成! 接下来:")
        print("1. 启动服务器: python server.py")
        print("2. 运行客户端: python client.py")
        print("3. 快速测试: python client.py --test")
        print("=" * 50)

    sys.exit(0 if success else 1)